//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programowanie_SSprint
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSprintEntities : DbContext
    {
        public SSprintEntities()
            : base("name=SSprintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<colors> colors { get; set; }
        public virtual DbSet<companies> companies { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<pictures> pictures { get; set; }
        public virtual DbSet<styles> styles { get; set; }
        public virtual DbSet<tshirts> tshirts { get; set; }
        public virtual DbSet<singleItemOrder> singleItemOrder { get; set; }
    }
}
