//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programowanie_SSprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.singleItemOrders = new HashSet<singleItemOrder>();
        }
    
        public int id { get; set; }
        public int status { get; set; }
        public Nullable<int> picture_id { get; set; }
        public string client_name { get; set; }
        public string client_email { get; set; }
        public string client_phone { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime order_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<singleItemOrder> singleItemOrders { get; set; }
        public virtual picture picture { get; set; }
    }
}
