//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programowanie_SSprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class singleItemOrder
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int tshirt_id { get; set; }
        public int amount { get; set; }
    
        public virtual order order { get; set; }
        public virtual tshirt tshirt { get; set; }
    }
}
