//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programowanie_SSprint
{
    using System;
    using System.Collections.Generic;
    
    public partial class tshirt : Communicator.CommunicatorElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tshirt()
        {
            this.singleItemOrders = new HashSet<singleItemOrder>();
        }
    
        public int id { get; set; }
        public int company_id { get; set; }
        public int style_id { get; set; }
        public string sex { get; set; }
        public int color_id { get; set; }
        public int in_stock { get; set; }
        public int default_loss_percentage { get; set; }
        public string size { get; set; }
    
        public virtual color color { get; set; }
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<singleItemOrder> singleItemOrders { get; set; }
        public virtual style style { get; set; }

        public override int getId()
        {
            return id;
        }
    }
}
